// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "it-ku/app/usercenter/cmd/api/internal/handler/user"
	"it-ku/app/usercenter/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/registerWithPhone",
				Handler: user.RegisterWithPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/registerWithEmail",
				Handler: user.RegisterWithEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/loginWithPhone",
				Handler: user.LoginWithPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/loginWithEmail",
				Handler: user.LoginWithEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)
}
