// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Sex      int64   `json:"sex"`
	Avatar   string `json:"avatar"`
}

type LoginSuccessResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type MobileRegisterReq struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
}

type EmailRegisterReq struct {
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}

type LoginWithEmailReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginWithPhoneReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userinfo"`
}
