// Code generated by goctl. DO NOT EDIT!
// Source: identity.proto

package identity

import (
	"context"

	"it-ku/app/identity/cmd/rpc/pb"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClearTokenReq     = pb.ClearTokenReq
	ClearTokenResp    = pb.ClearTokenResp
	GenerateTokenReq  = pb.GenerateTokenReq
	GenerateTokenResp = pb.GenerateTokenResp
	ValidateTokenReq  = pb.ValidateTokenReq
	ValidateTokenResp = pb.ValidateTokenResp

	Identity interface {
		//  生成token, 只让用户服务访问
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		//  清理token, 只让用户服务访问
		ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

//  生成token, 只让用户服务访问
func (m *defaultIdentity) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

//  清理token, 只让用户服务访问
func (m *defaultIdentity) ClearToken(ctx context.Context, in *ClearTokenReq, opts ...grpc.CallOption) (*ClearTokenResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.ClearToken(ctx, in, opts...)
}

func (m *defaultIdentity) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}
