// Code generated by goctl. DO NOT EDIT!
// Source: identity.proto

package server

import (
	"context"

	"it-ku/app/identity/cmd/rpc/internal/logic"
	"it-ku/app/identity/cmd/rpc/internal/svc"
	"it-ku/app/identity/cmd/rpc/pb"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

//  生成token, 只让用户服务访问
func (s *IdentityServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

//  清理token, 只让用户服务访问
func (s *IdentityServer) ClearToken(ctx context.Context, in *pb.ClearTokenReq) (*pb.ClearTokenResp, error) {
	l := logic.NewClearTokenLogic(ctx, s.svcCtx)
	return l.ClearToken(in)
}

func (s *IdentityServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenReq) (*pb.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}
